name: Get RC defaults
on: [workflow_dispatch]
jobs:
  getrcdef:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Upload strings
        run: |
          yarn install
          printenv GOOGLE_JSON > creds.json
          gulp get
        env:
          GOOGLE_JSON: ${{ secrets.FIREBASE_PROD_JSON }}
          GOOGLE_APPLICATION_CREDENTIALS: creds.json
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: res
          path: res
