name: OneSky (uploads strings to OneSky)
on:
  push:
    branches:
    - main
jobs:
  onesky:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Upload strings
        run: |
          yarn install
          gulp up
        env:
          SKYAPP_SECRET_KEY: ${{ secrets.SKYAPP_SECRET_KEY }}
