name: Upload strings to OneSky
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Upload strings
        run: |
          yarn install
          gulp up
        env:
          SKYAPP_SECRET_KEY: ${{ secrets.SKYAPP_SECRET_KEY }}
